name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  clang-format:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Lint
      uses: DoozyX/clang-format-lint-action@v0.17
      with:
        clangFormatVersion: 14
  build:
    needs: clang-format
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Conan
        run: pip install conan==2.0.16
      - name: Configure Conan
        run: conan profile detect
      - name: Install Conan packages
        run: conan install . --output-folder=build --build=missing --settings compiler=gcc --settings compiler.cppstd=17 --settings build_type=Release
      - name: Configure
        run: cmake --preset conan-release -DCPACK_PACKAGE_CONTACT="${{ secrets.CONTACT }}"
      - name: Build
        run: cmake --build --preset conan-release
      - name: Test
        working-directory: build
        run: ctest --verbose --preset conan-release
      - name: Pack
        working-directory: build
        run: cpack -G "DEB"
      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          path: build/*.deb
